language: c++

compiler: gcc

script: make && make test

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5

# Handle git submodules yourself
# http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci
git:
    submodules: false

before_install:
    - sed -i  's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

